language: ruby
rvm:
  - 2.0.0

install: "bin/wad -v"
# Note that WAD doesn't clean up old bundles for you. If you change Gemfile.lock a lot and the bucket becomes very large, you probably want to clean out old bundles once in a while.

script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rspec --tag integration
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database g5_content_management_system_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  campfire:
    rooms:
      secure: kp3AoXOS91YPScPGF/i4fWOKlG3HiMEdW4fJZKlAiQsKIBTjh5R4VnvwbSAfG62bb2LaERlgq3G3uKE5X1ayRA0BG7hMYXmK1pK8KMQfQF2iOo9FgLn8qW9bdFrg/e0KWNtFimjL+oBoT7zOlCQEXWfMoMbMeaICiSxnFdIg6U0=
    template:
      - "%{repository}#%{build_number} %{message} (%{branch} - %{commit} : %{author}) Change view : %{compare_url} Build details : %{build_url}"
    on_success: change
    on_failure: always
env:
  global:
    - S3_REGION=us-west-2
    - S3_BUCKET_NAME=cms-travis-cache
    - secure: "heRZxcYMYyUeQ7zMNJvXlYmc0QRN5+BNkexnzpgbOIwwxclZ8RyB5ax7yGoPakDTWxuYGV2oa6dcUkNuDKHsYm2p1v5p6OFJoT5c84mF3rHj5yFjRcI+S390kwWR0IV0BgNo/cj5d3er01u4Qgau087ip9r8SCZ7lc2fS/y4N/E="
