language: ruby
rvm:
  - 2.1.3

install: "bin/wad -v"
# Note that WAD doesn't clean up old bundles for you. If you change Gemfile.lock a lot and the bucket becomes very large, you probably want to clean out old bundles once in a while.

script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rspec --tag $(echo $RSPEC_TAG)
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database g5_content_management_system_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  campfire:
    rooms:
      secure: "CSoJcsijaW8+9XoQbXlP8WIv0pZGUs7JEFhyDMglVPlROms7Qe/hA/OB65wjinoC/33rsaNaxEgpOq8w1G8SJkFMUrI7QlevXD0qeDxS7puhvu/StBHY6YMohiSbVc1G+4ubI5RxBoVf1/5CakcDIouUxXXSMbkcgncFFGrB5/M="
    template:
      - "%{repository}#%{build_number} %{message} (%{branch} - %{commit} : %{author}) Change view : %{compare_url} Build details : %{build_url}"
    on_success: change
    on_failure: always
env:
  global:
    - S3_REGION=us-west-2
    - S3_BUCKET_NAME=cms-travis-cache
    - secure: "heRZxcYMYyUeQ7zMNJvXlYmc0QRN5+BNkexnzpgbOIwwxclZ8RyB5ax7yGoPakDTWxuYGV2oa6dcUkNuDKHsYm2p1v5p6OFJoT5c84mF3rHj5yFjRcI+S390kwWR0IV0BgNo/cj5d3er01u4Qgau087ip9r8SCZ7lc2fS/y4N/E="
  matrix:
    - RSPEC_TAG=~integration
    - RSPEC_TAG=integration
