:content_stripe:
  :slug: content-stripe
  :row_layout: single
  :widgets:
  - :slug: column
    :row_count: three
    :widgets:
    - :slug: calls-to-action
    - :slug: photo
    - :slug: home-page-multifamily-iui