---
:content_stripe_widget_seeder:
  :slug: content-stripe
  :row_layout: single
  :widgets:
  - :slug: column
    :row_count: two
    :widgets:
    - :slug: gallery-basic
    - :slug: multi-family-mini-search
