---
:slug: content-stripe
:row_css_custom: ''
:row_layout: thirds
:widgets:
- :slug: html
  :settings:
  - :name: text
    :value: "<p style=\"text-align:center\"><img alt=\"\" src=\"http://placehold.it/75x75/\"
      style=\"border-style:solid; border-width:0px\" /></p>\r\n\r\n<h3 style=\"text-align:center\">Pay
      Online</h3>\r\n"
- :slug: html
  :settings:
  - :name: text
    :value: "<p style=\"text-align:center\"><a href=\"/apartments/{{location_state}}/{{location_city}}/maintenance-request\"><img
      alt=\"\" src=\"http://placehold.it/75x75/\" style=\"border-style:solid; border-width:0px\"
      /></a></p>\r\n\r\n<h3 style=\"text-align:center\"><a href=\"/apartments/{{location_state}}/{{location_city}}/maintenance-request\">Maintenance
      Request</a></h3>\r\n"
- :slug: html
  :settings:
  - :name: text
    :value: "<p style=\"text-align:center\"><a href=\"/apartments/{{location_state}}/{{location_city}}/pet-friendly\"><img
      alt=\"\" src=\"http://placehold.it/75x75/\" style=\"border-style:solid; border-width:0px\"
      /></a></p>\r\n\r\n<h3 style=\"text-align:center\"><a href=\"/apartments/{{location_state}}/{{location_city}}/pet-friendly\">Pet
      Friendly</a></h3>\r\n"
