---
content_stripe:
  :slug: content-stripe
  :row_layout: thirds
  :widgets:
  - :slug: column
    :row_count: two
    :widgets:
    - :slug: html
  - :slug: column
    :row_count: two
    :widgets:
    - :slug: html
