---
:slug: content-stripe
:row_css_custom: ''
:row_layout: thirds
:widgets:
- :slug: column
  :row_count: one
  :widgets:
  - :slug: html
    :settings:
    - :name: text
      :value: "<h2>Shopping</h2>\r\n\r\n<ul>\r\n\t<li>One</li>\r\n\t<li>Two</li>\r\n\t<li>Three</li>\r\n</ul>\r\n\r\n<h2>Dining</h2>\r\n\r\n<ul>\r\n\t<li>One</li>\r\n\t<li>Two</li>\r\n\t<li>Three</li>\r\n</ul>\r\n"
- :slug: column
  :row_count: one
  :widgets:
  - :slug: html
    :settings:
    - :name: text
      :value: "<h2>Schools</h2>\r\n\r\n<ul>\r\n\t<li>One</li>\r\n\t<li>Two</li>\r\n\t<li>Three</li>\r\n</ul>\r\n\r\n<h2>Employers</h2>\r\n\r\n<ul>\r\n\t<li>One</li>\r\n\t<li>Two</li>\r\n\t<li>Three</li>\r\n</ul>\r\n"
- :slug: column
  :row_count: one
  :widgets:
  - :slug: photo
    :settings:
    - :name: photo_source_url
      :value: http://placehold.it/350x250
    - :name: photo_alignment
      :value: photo-block
