---
content_stripe:
  :slug: content-stripe
  :row_layout: uneven-thirds-2
  :widgets:
  - :slug: column
    :row_count: two
    :widgets:
    - :slug: photo
    - :slug: html
  - :slug: column
    :row_count: three
    :widgets:
    - :slug: navigation
      :settings:
      - :name: display_navigation
        :value: 'true'
      - :name: display_as_calls_to_action
        :value: 'true'
    - :slug: contact-info
    - :slug: social-links
