---
content_stripe:
  :slug: content-stripe
  :row_layout: uneven-thirds-2
  :widgets:
  - :slug: column
    :row_count: two
    :widgets:
    - :slug: html
    - :slug: lead-form
  - :slug: column
    :row_count: one
    :widgets:
    - :slug: html
