---
:slug: content-stripe
:row_css_custom: ''
:row_layout: uneven-thirds-2
:widgets:
- :slug: column
  :row_count: two
  :widgets:
  - :slug: html
    :settings:
    - :name: text
      :value: "<h1>{{location_name}} Reviews</h1>\r\n\r\n<p>Reviews are very important
        to us and are the best way to let others know if our team has provided you
        with a great experience. Write a Review.</p>\r\n\r\n<p><a href=\"https://reputation.g5search.com/\"
        target=\"_blank\">Reputation Manager Login</a></p>\r\n"
  - :slug: promoted-reviews
    :settings: []
- :slug: column
  :row_count: two
  :widgets:
  - :slug: calls-to-action
    :settings:
    - :name: cta_text_1
      :value: Contact Us
    - :name: page_slug_1
      :value: floor-plans
  - :slug: contact-info
    :settings:
    - :name: location_name
      :value: "{{ location_name }}"
    - :name: location_street_address
      :value: "{{ location_street_address}}"
    - :name: location_city
      :value: "{{ location_city }}"
    - :name: location_postal_code
      :value: "{{ location_postal_code }}"
    - :name: location_tel
      :value: "{{ location_phone_number }}"
    - :name: location_email
      :value: "/apartments/{{location_state_slug}}/{{location_city_slug}}/contact-us"
    - :name: maps_url
      :value: "/apartments/{{location_state_slug}}/{{location_city_slug}}/map-and-directions"
