---
:slug: content-stripe
:row_layout: uneven-thirds-2
:widgets:
- :slug: column
  :row_count: three
  :widgets:
  - :slug: html
  - :slug: promoted-reviews
- :slug: column
  :row_count: three
  :widgets:
  - :slug: contact-info
  - :slug: social-links
