---
content_stripe:
  :slug: content-stripe
  :row_layout: uneven-thirds-2
  :widgets:
  - :slug: html
  - :slug: column
    :row_count: four
    :widgets:
    - :slug: photo
    - :slug: calls-to-action
    - :slug: contact-info
    - :slug: social-links
