---
content_stripe:
  :slug: content-stripe
  :row_layout: uneven-thirds-2
  :widgets:
  - :slug: column
    :row_count: two
    :widgets:
    - :slug: html
    - :slug: gallery
  - :slug: column
    :row_count: two
    :widgets:
    - :slug: calls-to-action
    - :slug: contact-info
