---
:slug: content-stripe
:row_layout: uneven-thirds-2
:widgets:
- :slug: column
  :row_count: two
  :widgets:
  - :slug: html
  - :slug: floorplans-cards
- :slug: column
  :row_count: two
  :widgets:
  - :slug: contact-info
