---
content_stripe:
  :slug: content-stripe
  :row_layout: uneven-thirds-2
  :widgets:
  - :slug: gallery
  - :slug: column
    :row_count: three
    :widgets:
    - :slug: contact-info
    - :slug: social-links
