---
:name: Maintenance Request
:title: Maintenance Request at {{location_name}}
:enabled: true
:drop_targets:
- :html_id: drop-target-main
  :widgets:
  - :slug: meta-description
    :settings:
    - :name: meta_description
      :value: Visit the {{location_name}} website to submit a maintenance request.
        We are here to help.
  - :slug: photo
    :settings:
    - :name: photo_source_url
      :value: http://placehold.it/1600x250
    - :name: photo_alignment
      :value: photo-block
    - :name: photo_alt_tag
      :value: Submit your maintenance requests online
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: uneven-thirds-2
    :widgets:
    - :slug: column
      :row_count: two
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h1>Maintenance Request</h1>\r\n"
      - :slug: lead-form
