---
:name: Amenities
:title: "{{location_city}} {{location_qualifier}} Apartment Amenities at {{location_name}}"
:enabled: true
:drop_targets:
- :html_id: drop-target-main
  :widgets:
  - :slug: meta-description
    :settings:
    - :name: meta_description
      :value: "{{location_city}} {{location_qualifier}} apartment amenities are designed
        to meet all your needs at {{location_name}}. We are located near {{location_primary_landmark}}
        in {{location_city}}, {{location_state}}. "
  - :slug: photo
    :settings:
    - :name: photo_source_url
      :value: http://placehold.it/1600x250
    - :name: photo_alignment
      :value: photo-block
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: uneven-thirds-2
    :widgets:
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h1>Amenities</h1>\r\n\r\n<p>Lorem ipsum dolor sit amet, est te
            volutpat torquatos, nibh sale vocent te vix. Mei cu illud quaeque, probo
            veniam has cu, eu brute blandit praesent nec. Vero mundi adipiscing et
            usu, et quodsi lobortis atomorum pri. At vel dicant incorrupte, no vix
            ridens discere reprimique, ullum convenire intellegam no nam.</p>\r\n\r\n<p>No
            eam quaeque repudiare percipitur. Sed no dictas vocibus dissentiunt, dictas
            quaestio cum no, ius dico summo laoreet ex. Eum odio ipsum ex. Sit natum
            evertitur ex, quo at officiis assentior. Nibh congue est eu, suas nullam
            fastidii ne vix, fugit appetere consectetuer vix ex. Scripta delenit sea
            id, est ipsum mazim no. Ad delectus voluptatibus est, duo fugit definitiones
            an.</p>\r\n"
    - :slug: column
      :row_count: two
      :widgets:
      - :slug: calls-to-action
        :settings:
        - :name: cta_text_1
          :value: Contact Us
        - :name: page_slug_1
          :value: floor-plans
      - :slug: contact-info
        :settings:
        - :name: maps_url
          :value: "#"
        - :name: location_email
          :value: "#"
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: thirds
    :widgets:
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h2>Community Amenities:</h2>\r\n\r\n<ul>\r\n\t<li>One</li>\r\n\t<li>Two</li>\r\n\t<li>Three</li>\r\n\t<li>Four</li>\r\n\t<li>Five</li>\r\n\t<li>Six</li>\r\n\t<li>Seven</li>\r\n\t<li>Eight</li>\r\n</ul>\r\n"
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h2>Apartment Features:</h2>\r\n\r\n<ul>\r\n\t<li>One</li>\r\n\t<li>Two</li>\r\n\t<li>Three</li>\r\n\t<li>Four</li>\r\n\t<li>Five</li>\r\n\t<li>Six</li>\r\n\t<li>Seven</li>\r\n\t<li>Eight</li>\r\n</ul>\r\n"
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: photo
        :settings:
        - :name: photo_source_url
          :value: http://placehold.it/350x295
        - :name: photo_alignment
          :value: photo-block
