---
:name: Schedule a Tour
:title: Schedule a Tour of {{location_name}}
:enabled: true
:drop_targets:
- :html_id: drop-target-main
  :widgets:
  - :slug: meta-description
    :settings:
    - :name: meta_description
      :value: We welcome you to tour {{location_name}} in person. Schdule your tour
        online or call {{location_marketing_number}}!
  - :slug: photo
    :settings:
    - :name: photo_source_url
      :value: http://placehold.it/1600x250
    - :name: photo_alignment
      :value: photo-block
    - :name: photo_alt_tag
      :value: Schedule a tour to view our apartments in {{ location_city }}, {{ location_state
        }}
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: uneven-thirds-2
    :widgets:
    - :slug: column
      :row_count: two
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h1>Schedule a Tour</h1>\r\n"
      - :slug: lead-form
