---
:name: Contact Us
:title: Contact {{location_name}} in {{location_city}}
:enabled: true
:drop_targets:
- :html_id: drop-target-main
  :widgets:
  - :slug: meta-description
    :settings:
    - :name: meta_description
      :value: Contact {{location_name}} to learn more about our apartment rentals
        in {{location_city}}, {{location_state}}. We are dedicated to creating a great
        living experience.
  - :slug: photo
    :settings:
    - :name: photo_source_url
      :value: http://placehold.it/1600x250
    - :name: photo_alignment
      :value: photo-block
    - :name: photo_alt_tag
      :value: Contact {{ location_name }} for information about our apartments in
        {{ location_city }}
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: uneven-thirds-2
    :widgets:
    - :slug: column
      :row_count: two
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h1>Contact {{location_name}}</h1>\r\n"
      - :slug: lead-form
    - :slug: column
      :row_count: 
      :widgets: []
