---
:name: EEO Statement
:title: "{{location_name}} | EEO Statement "
:enabled: true
:drop_targets:
- :html_id: drop-target-main
  :widgets:
  - :slug: meta-description
    :settings:
    - :name: meta_description
      :value: "{{location_name}} is an Equal Opportunity Employer.  Visit our site
        for our Equal Employment Opportunity statement."
  - :slug: photo
    :settings:
    - :name: photo_source_url
      :value: http://placehold.it/1600x250
    - :name: photo_alignment
      :value: photo-block
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: uneven-thirds-2
    :widgets:
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h1>Equal Employment Opportunity Statement</h1>\r\n\r\n<p>Lorem
            ipsum dolor sit amet, natum erant luptatum ea pri, feugiat minimum eligendi
            pri ex. Sit eu odio dolores, vel noster conceptam ei, ius te sonet philosophia.
            Eu vix soluta noluisse, simul dissentias sea ea, ei eos copiosae oporteat
            scribentur. Mel cu brute quodsi detracto, aperiri accusata adversarium
            sed an. Omnis sonet mel ex, eu mea sint maiorum eligendi. Eu mea utroque
            abhorreant. Vel an luptatum laboramus, per at illum probatus.</p>\r\n"
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: photo
        :settings:
        - :name: photo_source_url
          :value: http://placehold.it/450x300
        - :name: photo_alignment
          :value: photo-block
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: halves
    :widgets:
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h2>Heading</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, natum erant
            luptatum ea pri, feugiat minimum eligendi pri ex. Sit eu odio dolores,
            vel noster conceptam ei, ius te sonet philosophia. Eu vix soluta noluisse,
            simul dissentias sea ea, ei eos copiosae oporteat scribentur. Mel cu brute
            quodsi detracto, aperiri accusata adversarium sed an. Omnis sonet mel
            ex, eu mea sint maiorum eligendi. Eu mea utroque abhorreant. Vel an luptatum
            laboramus, per at illum probatus.</p>\r\n"
    - :slug: column
      :row_count: one
      :widgets:
      - :slug: photo
        :settings:
        - :name: photo_source_url
          :value: http://placehold.it/505x400
        - :name: photo_alignment
          :value: photo-block
