---
:name: Privacy Policy
:title: "{{location_name}} Privacy Policy"
:enabled: true
:drop_targets:
- :html_id: drop-target-main
  :widgets:
  - :slug: meta-description
    :settings:
    - :name: meta_description
      :value: "{{location_name}} collects your information only to provide the best
        possible service and we never share what you provide. View our privacy policy
        at our website."
  - :slug: photo
    :settings:
    - :name: photo_source_url
      :value: http://placehold.it/1600x250
    - :name: photo_alignment
      :value: photo-block
  - :slug: content-stripe
    :row_css_custom: ''
    :row_layout: single
    :widgets:
    - :slug: html
      :settings:
      - :name: text
        :value: "<h1>{{client_name}} Privacy Policy</h1>\r\n \r\n<p>Thank you for
          visiting {{client_name}}’s (\"[CLIENT]\") Internet web site (\"Site\") located
          at the URL {{client_domain}}. This Privacy Policy details certain policies
          implemented throughout [CLIENT] governing [CLIENT]'s collection and use
          of personally identifiable information about users of our Site and our services.
          </p>\r\n \r\n<h2>Privacy Policy Updates</h2>\r\n<p>Due to the Internet's
          rapidly evolving nature, [CLIENT] may need to update this Privacy Policy
          from time to time.  If so, [CLIENT] will post its updated Privacy Policy
          on our Site along with a change notice on the Site.  [CLIENT] may also send
          registered users of our services a notice that this Privacy Policy has been
          changed.  [CLIENT] encourages you to review this Privacy Policy regularly
          for any changes.  Your continued use of this Site and/or services and/or
          your continued provision of personally identifiable information to us after
          the posting of such notice will be subject to the terms of the then-current
          Privacy Policy.</p>\r\n<h2>Information Collection</h2>\r\n<p>You can generally
          visit our Site without revealing any personally identifiable information
          about yourself.  However, in certain sections of this Site, we may require
          you to submit your personally identifiable information to us and we may
          invite you to submit questions, comments and request information.</p>\r\n<p>Due
          to the nature of some of our services, you may provide us with personally
          identifiable information such as your name, email address, username, password,
          address, phone number, and other contact information<!-- [WORK WITH YOUR
          COUNSEL TO INCLUDE ANY OTHER TYPE OF INFORMATION THAT IS COLLECTED]  -->
          that you voluntarily transmit with your communication to us.</p>\r\n<h2>Information
          Use</h2>\r\n<p>We may use your personally identifiable information to deliver
          our services or information you have requested, verify your authority to
          enter certain password protected areas of the Site, verify that you are
          a customer or prospective customer, send you information that you have signed
          up to receive, notices about our products and/or services that you have
          used or that may be of interest to you and notices about events, and improve
          the content and general administration of the Site and our services.</p><!--[WORK
          WITH YOUR COUNSEL TO INCLUDE HOW YOU USE THE INFORMATION]-->\r\n<p>If you
          are a user of our services, we may use your personally identifiable information
          to provide the services to you.</p>\r\n<h2>Children's Privacy</h2>\r\n<p>[CLIENT]
          recognizes the privacy interests of children and we encourage parents and
          guardians to take an active role in their children's online activities and
          interests.  Neither our Site nor our services are intended for children
          under the age of 13.  [CLIENT] does not target its services or this Site
          to children under 13.  [CLIENT] does not knowingly collect personally identifiable
          information from children under the age of 13.</p><!--[NOTE- CLIENT CANNOT
          COLLECT AGE INFORMATION ON THE SITE AND IF CLIENT DOES COLLECT AGE, YOU
          MUST DELETE AND NOT USE INFORMATION FROM A USER UNDER THE AGE OF 13. WORK
          WITH YOUR COUNSEL TO ACCURATELY ADJUST THIS SECTION]-->\r\n<h2>Cookies</h2>\r\n
          \r\n<p>We use both session ID cookies and persistent cookies. A session
          ID cookie expires when you close your browser. A persistent cookie remains
          on your hard drive for an extended period of time. You can remove persistent
          cookies by following directions provided in your Internet browser's \"help\"
          file.</p>\r\n \r\n<p>On our Site, we use session cookies to make it easier
          for you to navigate the Site by remembering your locale preferences and
          to improve and track the overall Site experience.  For our Site, we set
          a persistent cookie to authenticate your login and authorization to use
          the services. Persistent cookies enable us to track, store and target the
          interests of our users to enhance the experience on our Site.  If you reject
          cookies, you may still use our Site, but your ability to use some areas
          of our Site may be limited.</p>\r\n \r\n<h2>Third Party Analytics Tools</h2>\r\n<!--[WORK
          WITH YOUR COUNSEL TO ADJUST THIS SECTION TO REFLECT YOUR PRACTICES]-->\r\n
          \r\n<p>Beyond the personally identifiable information you voluntarily provide
          to us, [CLIENT] utilizes analytics tools including third party technologies,
          such as Google Analytics, to collect non-personally identifiable information
          utilizing cookies. Certain types of information, including geolocation,
          device type, onsite website usage and behavior, demographic data, and purchase
          history, is collected and aggregated across [CLIENT] Site users for our
          analysis and advertising efforts.</p>\r\n \r\n<p>[CLIENT] uses Remarketing
          with Google Analytics and Google Adwords to display relevant advertisements
          to users who have previously visited our Site. Referred to as remarketing
          or retargeting, [CLIENT] may utilize previous session information to serve
          display advertisements to you on the Site and based on such session information
          Google may set a cookie and serve ads to you on third party websites on
          the Google Display Network. Third party vendors such as Google may display
          [CLIENT] ads on websites across the Internet.  Aggregated user data may
          be utilized to create remarketing/retargeting “lists,” or groups of users
          with similar onsite behaviors or demographics.</p>\r\n \r\n<p>[CLIENT] also
          uses Google Display Network Impression Reporting and Google Analytics Demographics
          and Interest Reporting and Interest-Based Advertising to display advertisements
          to users based on their inferred interests and demographics. [CLIENT] does
          not run interest-based advertising campaigns that collect personally identifiable
          information.</p>\r\n \r\n<p>Users may learn more about Google Analytics
          use of cookies by visiting the Google Privacy and Terms page at http://www.google.com/policies/.
          You may opt out of being tracked by Google Analytics by i) Turning off cookies
          in the preferences settings in your browser ii) Downloading the Google Analytics
          opt-out browser add on available at: https://tools.google.com/dlpage/gaoptout/
          \ iii) Opting out of user interest and demographic categories in the Settings
          for Google Ads feature to manage or opt out of Google interest based ads
          at: or iv) Managing cookies used for online advertising across multiple
          companies at the US-based Network Advertising Initiative at http://www.networkadvertising.org/choices/.</p>\r\n
          \r\n \r\n<h2>Aggregate Information</h2>\r\n<p>The Site may track the total
          number of visitors to our Site, the number of visitors to each page of our
          Site, browser type, IP addresses, External Web Sites (defined below) linked
          to and other aggregated data collected through our services and we may analyze
          this data for trends and statistics in the aggregate but such information
          will be maintained, used and disclosed in aggregate form only and it will
          not contain personally identifiable information.  We may use such aggregate
          information to analyze trends, administer the Site, track users' movement,
          and gather broad demographic information for aggregate use. </p>\r\n<h2>Disclosure
          of Personally Identifiable Information</h2>\r\n<p>We may provide your personally
          identifiable information and the data generated by cookies and third party
          analytics tools and the aggregate information to the vendors and service
          agencies that we may engage to assist us in providing our services to you.
          For example, we engage with G5 Search Marketing, Inc. to assist us in creating
          and hosting this Site.</p>  <!--[WORK WITH YOUR COUNSEL TO INCLUDE ANY OTHER
          DISCLOSURES OF PERSONAL DATA] -->\r\n<p>We will disclose your personally
          identifiable information if we reasonably believe we are required to do
          so by law, regulation or other government authority or to assist in any
          investigation, to protect our or our users' rights or to enforce our terms
          of use.  We will not sell your personally identifiable information to any
          company or organization except we may transfer your personally identifiable
          information to a successor entity upon a merger, consolidation or other
          corporate reorganization in which [CLIENT] participates or to a purchaser
          of all or substantially all of [CLIENT]'s assets to which this Site relates.</p>\r\n<h2>Links
          to Third Party Sites</h2>\r\n<p>The Site may provide links to other Web
          sites or resources over which [CLIENT] does not have control (\"External
          Web Sites\").  Such links do not constitute an endorsement by [CLIENT] of
          those External Web Sites.  You acknowledge that [CLIENT] is providing these
          links to you only as a convenience, and further agree that [CLIENT] is not
          responsible for the content of such External Web Sites.  Your use of External
          Web Sites is subject to the terms of use and privacy policies located on
          the linked to External Web Sites.</p>\r\n<h2>Security</h2>\r\n<p>We may
          employ industry standard procedural and technological measures that are
          reasonably designed to help protect your personally identifiable information
          from loss, unauthorized access, disclosure, alteration or destruction.  [CLIENT]
          may use, without limitation, firewalls, password protection, secure socket
          layer, and other security measures to help prevent unauthorized access to
          your personally identifiable information.</p><!--[WORK WITH YOUR COUNSEL
          TO INCLUDE OTHER SECURITY MEASURES OR ADJUST BASED ON SECURITY MEASURES
          USED ON THE SITE]-->\r\n<h2>Notice to European Users</h2>\r\n<p>This Site
          and the services on this Site are targeted for users in the United States
          of America.  Any information you enter on this Site may be transferred outside
          of the European Union to the United States of America which does not offer
          an equivalent level of protection to that required in the European Union.
          In particular, you are advised that the United States of America uses a
          sectoral model of privacy protection that relies on a mix of legislation,
          governmental regulation, and self-regulation. Article 26 of the European
          Union’s Data Protection Directive (Directive 95/46/EC, 1995 O.J. (L 281)
          31) allows for transfer of personal data from the European Union to a third
          country if the individual has unambiguously given his consent to the transfer
          of personal information, regardless of the third country's level of protection.
          By using this Site or the services, you consent to the transfer of all such
          information to the United States of America which may not offer an equivalent
          level of protection to that required in the European Union and to the processing
          of that information by [CLIENT] on its servers located in the United States
          of America as described in this Privacy Policy.</p>\r\n<h2>Questions</h2>\r\n<p>If
          you have any questions regarding this Privacy Policy please contact us.</p>\r\n\r\n<p>This
          Privacy Policy was last updated: <strong>{{page_updated}}</strong></p>\r\n<p>This
          Privacy Policy is effective as of: <strong>{{page_created}}</strong></p>\r\n\r\n"
