---
web_page_template:
  :name: Home
  :title: Apartments in {{location_city}}, {{location_state}} | {{location_name}}
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: 'Learn about Chatham Wood Apartments in Chatham Woods High Point by
          visiting our website today. '
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: column
        :row_count: three
        :widgets:
        - :slug: calls-to-action
        - :slug: photo
        - :slug: home-page-multifamily-iui
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: html
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: contact-info
        - :slug: social-links
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: html
      - :slug: map
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: gallery
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: photo
      - :slug: social-feed
