---
web_page_templates:
  :name: Home
  :title: 'CompassRock Real Estate Offering Property Management & Construction Services '
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: At {{location_name}} we are dedicated to providing the best in apartment
          homes. To learn more about our apartment communities, please visit our website.
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: gallery-basic
        - :slug: multi-family-mini-search
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: column
        :row_count: six
        :widgets:
        - :slug: html
        - :slug: button
        - :slug: button
        - :slug: button
        - :slug: button
        - :slug: button
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: html
      - :slug: corporate-locations-map
    - :slug: content-stripe
      :row_layout: uneven-thirds-1
      :widgets:
      - :slug: html
      - :slug: photo
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: gallery
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: featured-property-gallery
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: video
      - :slug: html
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: html
      - :slug: photo
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: photo
      - :slug: html
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: html
      - :slug: photo
