---
web_page_templates:
  :name: Photos
  :title: Photos of Our Apartments in {{location_city}}, {{location_state}} | {{location_name}}
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: For photos of apartments in {{location_city}} or to see your new apartment
          home visit the {{location_name}} website today for more information.
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: html
      - :slug: calls-to-action
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: gallery
        - :slug: html
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: contact-info
        - :slug: social-links
