website:

  website_template:
    name: Website Template
    web_layout:
      slug: main-first-sidebar-right
    web_theme:
      slug: high-rise
    drop_targets:
      - html_id: drop-target-head
        widgets:
          - slug: meta
          - slug: typekit
          - slug: analytics
      - html_id: drop-target-logo
        widgets:
          - slug: logo
      - html_id: drop-target-phone
        widgets:
          - slug: phone
      - html_id: drop-target-btn
        widgets:
          - slug: button
      - html_id: drop-target-nav
        widgets:
          - slug: navigation
      - html_id: drop-target-aside-before-main
        widgets:
          - slug: navigation
      - html_id: drop-target-aside-after-main
        widgets:
          - slug: contact-info
          - slug: social-links
          - slug: photo
          - slug: html
          - slug: coupon
      - html_id: drop-target-footer
        widgets:
          - slug: contact-info
          - slug: hours
          - slug: footer-info

  web_home_template:
    name: Home
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: photo
          - slug: html

  web_page_templates:
    - name: Amenities
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: html
            - slug: photo
            - slug: photo

    - name: Coupon
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: coupon

    - name: Floorplans and Rates
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: floorplans

    - name: Directions
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: directions

    - name: Photo Gallery
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: gallery

    - name: Request Info
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: html
            - slug: request-info-form

    - name: Social
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: html
            - slug: blog-feed
            - slug: twitter-feed

    - name: Social
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: html
            - slug: blog-feed
            - slug: twitter-feed

    - name: Neighborhood
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - slug: html
            - slug: photo
            - slug: photo
            - slug: html
