website:

  website_template:
    name: Website Template
    web_layout:
      name: main-first-sidebar-right
    web_theme:
      name: high-rise
    drop_targets:
      - html_id: drop-target-head
        widgets:
          - name: meta
      - html_id: drop-target-logo
        widgets:
          - name: logo
      - html_id: drop-target-phone
        widgets:
          - name: phone
      - html_id: drop-target-btn
        widgets:
          - name: button
      - html_id: drop-target-nav
        widgets:
          - name: navigation
      - html_id: drop-target-aside
        widgets:
          - name: calls-to-action
          - name: contact-info
          - name: social-links
          - name: photo
          - name: html
          - name: coupon
      - html_id: drop-target-footer
        widgets:
          - name: navigation
          - name: contact-info
          - name: hours
          - name: footer-info
          - name: analytics

  web_home_template:
    name: Home
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - name: photo
          - name: html

  web_page_templates:
    - name: Amenities
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: html
            - name: photo
            - name: photo

    - name: Coupon
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: coupon

    - name: Floorplans and Rates
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: floorplans

    - name: Directions
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: directions

    - name: Photo Gallery
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: gallery

    - name: Request Info
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: html
            - name: request-info-form

    - name: Social
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: html
            - name: blog-feed
            - name: twitter-feed

    - name: Social
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: html
            - name: blog-feed
            - name: twitter-feed

    - name: Neighborhood
      drop_targets:
        - html_id: drop-target-main
          widgets:
            - name: html
            - name: photo
            - name: photo
            - name: html

