website_template:
  name: Website Template
  web_layout:
    slug: main-first-sidebar-right
  web_theme:
    slug: high-rise
  drop_targets:
    - html_id: drop-target-head
      widgets:
        - slug: meta
        - slug: typekit
        - slug: analytics
    - html_id: drop-target-logo
      widgets:
        - slug: logo
    - html_id: drop-target-phone
      widgets:
        - slug: phone
    - html_id: drop-target-btn
      widgets:
        - slug: button
    - html_id: drop-target-nav
      widgets:
        - slug: navigation
    - html_id: drop-target-aside-before-main
      widgets:
        - slug: navigation
          settings:
            - name: display_as_calls_to_action
              value: "true"
    - html_id: drop-target-aside-after-main
      widgets:
        - slug: contact-info
    - html_id: drop-target-footer
      widgets:
        - slug: contact-info
        - slug: hours
        - slug: footer-info

web_home_template:
  name: Home
  drop_targets:
    - html_id: drop-target-main
      widgets:
        - slug: photo
        - slug: html
        - slug: meta-description

web_page_templates:
  - name: Floor Plans
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: floor-plans
          - slug: html
          - slug: meta-description

  - name: Amenities
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Photo Gallery
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: gallery
          - slug: html
          - slug: meta-description

  - name: Neighborhood
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Map and Directions
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: map
          - slug: html
          - slug: meta-description

  - name: Residents
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: button
          - slug: button
          - slug: button
          - slug: button
          - slug: button
          - slug: html
          - slug: meta-description

  - name: Apply
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: apply-form
          - slug: html
          - slug: meta-description

  - name: Schedule Tour
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: tour-form
          - slug: html
          - slug: meta-description

  - name: Request Information
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: request-info-form
          - slug: html
          - slug: meta-description

  - name: Contact Us
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: contact-form
          - slug: html
          - slug: meta-description

  - name: Pet Friendly
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Community Events
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Maintenance Request
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: service-request-form
          - slug: html
          - slug: meta-description

  - name: Suggestion Box
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: suggestion-form
          - slug: html
          - slug: meta-description

  - name: Privacy Policy
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description
