website_template:
  name: Website Template
  web_layout:
    slug: main-first-sidebar-right
  web_theme:
    slug: high-rise
  drop_targets:
    - html_id: drop-target-head
      widgets:
        - slug: meta
        - slug: typekit
        - slug: analytics
    - html_id: drop-target-logo
      widgets:
        - slug: logo
    - html_id: drop-target-phone
      widgets:
        - slug: phone
    - html_id: drop-target-btn
      widgets:
        - slug: button
    - html_id: drop-target-nav
      widgets:
        - slug: navigation
    - html_id: drop-target-aside-before-main
      widgets:
        - slug: navigation
          settings:
            - name: display_as_calls_to_action
              value: "true"
    - html_id: drop-target-aside-after-main
      widgets:
        - slug: contact-info
    - html_id: drop-target-footer
      widgets:
        - slug: contact-info
        - slug: hours
        - slug: footer-info

web_home_template:
  name: Home
  title: "Apartments in {{location_neighborhood}} {{location_city}}"
  drop_targets:
    - html_id: drop-target-main
      widgets:
        - slug: photo
        - slug: html
        - slug: meta-description

web_page_templates:
  - name: Floor Plans
    title: "{{location_floor_plans}} Apartments in {{location_city}} with {{location_primary_amenity}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: floor-plans
          - slug: html
          - slug: meta-description

  - name: Amenities
    title: "{{location_city}} Apartment Amenities at {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Photo Gallery
    title: "Photos of Our Apartments in {{location_city}} | {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: gallery
          - slug: html
          - slug: meta-description

  - name: Neighborhood
    title: "{{location_neighborhood}} {{location_city}} Apartments near {{location_primary_landmark}} | {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Map and Directions
    title: "Directions to Apartments for rent in {{location_city}}, {{location_state}} | {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: map
          - slug: html
          - slug: meta-description

  - name: Residents
    title: "Information for Current Residents at {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
            settings:
              - name: text
                value: <h1>Information for Current Residents</h1>
          - slug: button
            settings:
              - name: button_label
                value: Maintenance Request
              - name: button_description
                value: Send a request to our maintenance department day or night
              - name: button_layout
                value: grid
          - slug: button
            settings:
              - name: button_label
                value: Pay Online
              - name: button_description
                value: Pay online using your checking account
              - name: button_layout
                value: grid
          - slug: button
            settings:
              - name: button_label
                value: Pet Friendly
              - name: button_description
                value: Looking to bring a pet into your home? View our pet policy for more information
              - name: button_layout
                value: grid
          - slug: button
            settings:
              - name: button_label
                value: Community Events
              - name: button_description
                value: Keep up with all the community events by viewing our events calendar
              - name: button_layout
                value: grid
          - slug: button
            settings:
              - name: button_label
                value: Suggestion Box
              - name: button_description
                value: We would love to know how we're doing. Use this form to send our staff feedback about our service or property
              - name: button_layout
                value: grid
          - slug: html
          - slug: meta-description

  - name: Apply
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: apply-form
          - slug: html
          - slug: meta-description

  - name: Schedule Tour
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: tour-form
          - slug: html
          - slug: meta-description

  - name: Request Information
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: request-info-form
          - slug: html
          - slug: meta-description

  - name: Contact Us
    title: "Contact {{location_name}} in {{location_city}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: contact-form
          - slug: html
          - slug: meta-description

  - name: Pet Friendly
    title: "Pet Friendly Apartments in {{location_city}} by {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Community Events
    title: "Events at {{location_name}} in {{location_city}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description

  - name: Maintenance Request
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: service-request-form
          - slug: html
          - slug: meta-description

  - name: Suggestion Box
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: suggestion-form
          - slug: html
          - slug: meta-description

  - name: Privacy Policy
    title: "{{location_name}}'s Privacy Policy"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: html
          - slug: meta-description
