website_template:
  name: Website Template
  web_layout:
    slug: rows
  web_theme:
    slug: high-rise
  drop_targets:
    - html_id: drop-target-head
      widgets:
        - slug: meta
        - slug: typekit
        - slug: analytics
    - html_id: drop-target-logo
      widgets:
        - slug: logo
    - html_id: drop-target-phone
      widgets:
        - slug: phone
    - html_id: drop-target-btn
      widgets:
        - slug: button
    - html_id: drop-target-nav
      widgets:
        - slug: navigation
    - html_id: drop-target-aside-before-main
      widgets:
        - slug: navigation
          settings:
            - name: display_as_calls_to_action
              value: "true"
    - html_id: drop-target-aside-after-main
      widgets:
        - slug: contact-info
    - html_id: drop-target-footer
      widgets:
        - slug: contact-info
        - slug: footer-info

web_home_template:
  name: Home
  title: "Apartments in {{location_neighborhood}} {{location_city}}"
  drop_targets:
    - html_id: drop-target-main
      widgets:
        - slug: content-stripe
        - slug: content-stripe
        - slug: content-stripe

web_page_templates:
  - name: Floor Plans
    title: "{{location_floor_plans}} Apartments in {{location_city}} with {{location_primary_amenity}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Amenities
    title: "{{location_city}} Apartment Amenities at {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Photo Gallery
    title: "Photos of Our Apartments in {{location_city}} | {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Neighborhood
    title: "{{location_neighborhood}} {{location_city}} Apartments near {{location_primary_landmark}} | {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Map and Directions
    title: "Directions to Apartments for rent in {{location_city}}, {{location_state}} | {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Residents
    title: "Information for Current Residents at {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Apply
    title: "Apply to live at {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Schedule Tour
    title: "Schedule a tour to view {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Request Information
    title: "Request information from {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Contact Us
    title: "Contact {{location_name}} in {{location_city}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Pet Friendly
    title: "Pet Friendly Apartments in {{location_city}} by {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Community Events
    title: "Events at {{location_name}} in {{location_city}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Maintenance Request
    title: "Maintenance request at {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Suggestion Box
    title: "Suggestion box at {{location_name}}"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Privacy Policy
    title: "{{location_name}}'s Privacy Policy"
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe
