website_template:
  name: Website Template
  web_layout:
    slug: rows
  web_theme:
    slug: luxe
  drop_targets:
    - html_id: drop-target-head
      widgets:
        - slug: meta
        - slug: typekit
        - slug: analytics
    - html_id: drop-target-logo
      widgets:
        - slug: logo
    - html_id: drop-target-btn
      widgets:
        - slug: button
    - html_id: drop-target-nav
      widgets:
        - slug: navigation
    - html_id: drop-target-aside-before-main
      widgets:
        - slug: navigation
          settings:
            - name: display_as_calls_to_action
              value: "true"
    - html_id: drop-target-aside-after-main
      widgets:
        - slug: contact-info
    - html_id: drop-target-footer
      widgets:
        - slug: contact-info
        - slug: footer-info

web_home_template:
  name: Home
  drop_targets:
    - html_id: drop-target-main
      widgets:
        - slug: content-stripe
        - slug: content-stripe
        - slug: content-stripe

web_page_templates:
  - name: Floor Plans
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Amenities
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Photo Gallery
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Neighborhood
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Map and Directions
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Residents
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Apply
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Schedule Tour
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Request Information
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Contact Us
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Pet Friendly
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Community Events
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Maintenance Request
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Suggestion Box
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe

  - name: Privacy Policy
    drop_targets:
      - html_id: drop-target-main
        widgets:
          - slug: content-stripe
          - slug: content-stripe
          - slug: content-stripe
