---
:website_template:
  :name: Website Template
  :web_layout:
    :slug: rows
  :web_theme:
    :slug: ivy
  :drop_targets:
  - :html_id: drop-target-head
    :widgets:
    - :slug: meta
    - :slug: typekit
    - :slug: analytics
  - :html_id: drop-target-logo
    :widgets:
    - :slug: logo
      :settings:
      - :name: business_name
        :value: "{{client_name}}"
      - :name: display_logo
        :value: 'true'
      - :name: logo_url
        :value: http://placehold.it/230x150/000/fff
  - :html_id: drop-target-phone
    :widgets: []
  - :html_id: drop-target-btn
    :widgets: []
  - :html_id: drop-target-nav
    :widgets:
    - :slug: navigation
      :settings:
      - :name: display_navigation
        :value: 'false'
      - :name: display_as_calls_to_action
        :value: 'false'
      - :name: display_corporate_navigation
        :value: 'false'
  - :html_id: drop-target-aside-before-main
    :widgets:
    - :slug: contact-info-sheet
      :settings: []
  - :html_id: drop-target-aside-after-main
    :widgets: []
  - :html_id: drop-target-footer
    :widgets:
    - :slug: contact-info
      :settings: []
    - :slug: footer-info
:web_home_template:
  :name: Home
  :title: "{{client_name}} | Apartments "
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: At {{client_name}} we are dedicated to providing the best in apartment
          homes.  To learn more about our apartment communities, please visit our
          website.
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: single
      :widgets:
      - :slug: column
        :row_count: three
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/1871x680
          - :name: photo_alignment
            :value: photo-block
        - :slug: calls-to-action
          :settings:
          - :name: cta_text_1
            :value: Contact Us
          - :name: page_slug_1
            :value: contact-us
        - :slug: city-state-zip-search
          :settings:
          - :name: search_results_page
            :value: "/our-communities"
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h1><span style=\"font-family:arial,sans,sans-serif\">Welcome
              to {{client_name}}</span></h1>\r\n\r\n<p>Lorem ipsum dolor sit amet,
              pri paulo quidam cu. Sea ad quot reque tantas, quaeque placerat maluisset
              pro ut. Ne ius antiopam interpretaris. Mazim oporteat reprehendunt per
              ea, semper assueverit mel id. Copiosae deseruisse no vix, cu labitur
              saperet praesent per.</p>\r\n\r\n<h2>Build Notes:</h2>\r\n\r\n<p>Build
              notes for Orion Themes:&nbsp;<a href=\"https://g5.jiveon.com/docs/DOC-7193\"
              target=\"_blank\">Theme / Blueprint Index (Hub)</a></p>\r\n\r\n<p>Build
              notes for Orion Widgets:&nbsp;<a href=\"https://g5.jiveon.com/docs/DOC-6923\"
              target=\"_blank\">Widget Index (Hub)</a></p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: corporate-locations-map
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: halves
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h2>Heading</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, eos ad
              tibique appetere scribentur, accusamus prodesset nec an. Nostrud adipiscing
              id mea, commodo copiosae mel ex. Essent causae eu pro, diam periculis
              reformidans usu et. An sit eros definiebas inciderint, dicunt inimicus
              praesent nam ei.</p>\r\n\r\n<p>Autem suavitate definitiones in eos,
              est omittam epicurei vulputate an, vel meis dicta atomorum ut. Quo scripta
              appareat hendrerit an, eum graeco dissentiet ex. Option mentitum sit
              at. Sit an falli choro vituperatoribus, at vix movet prompta constituam,
              eam et veri movet senserit. Luptatum signiferumque eum in. Omittam ponderum
              et mel, sea libris verterem recteque ut.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/540x400
          - :name: photo_alignment
            :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: single
      :widgets:
      - :slug: featured-property-gallery
        :settings:
        - :name: gallery_title
          :value: Featured Locations
        - :name: gallery_thumbnails
          :value: 'yes'
        - :name: gallery_mini
          :value: 'no'
        - :name: gallery_carousel
          :value: 'no'
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: video
          :settings:
          - :name: video_id
            :value: SkghXII4h7k
          - :name: video_title
            :value: Orion vs Fruit
          - :name: source
            :value: "//www.youtube.com/embed/"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: social-feed
:web_page_templates:
- :name: Our Communities
  :title: "{{client_name}} | Our Communities "
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: "{{client_name}} offers high quality apartment communities in your
          area."
    - :slug: photo
      :settings:
      - :name: photo_source_url
        :value: http://placehold.it/1600x250
      - :name: photo_alignment
        :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-1
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h1>{{client.branded_name}} Communities</h1>\r\n\r\n<p>Lorem
              ipsum dolor sit amet, viris lobortis sit in, ad usu diam magna, debet
              noster aliquid et est. Vis cu tota nostrum salutatus, nonumy ullamcorper
              contentiones nec id. Tota appareat percipit qui at, ius antiopam vulputate
              intellegebat ea. Eam labitur gubergren urbanitas ea, his cu wisi vitae,
              nisl mollis fierent mel te. Mel at saepe platonem, eos an illud aeterno
              abhorreant, in graeci regione sit. At dicit appetere eum.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: city-state-zip-search
          :settings: []
- :name: About Us
  :title: "{{client_name}} About Us"
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: Learn about {{client_name}} by visiting our website.
    - :slug: photo
      :settings:
      - :name: photo_source_url
        :value: http://placehold.it/1600x250
      - :name: photo_alignment
        :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h1>About {{ client_name }}</h1>\r\n\r\n<p>Lorem ipsum dolor
              sit amet, natum erant luptatum ea pri, feugiat minimum eligendi pri
              ex. Sit eu odio dolores, vel noster conceptam ei, ius te sonet philosophia.
              Eu vix soluta noluisse, simul dissentias sea ea, ei eos copiosae oporteat
              scribentur. Mel cu brute quodsi detracto, aperiri accusata adversarium
              sed an. Omnis sonet mel ex, eu mea sint maiorum eligendi. Eu mea utroque
              abhorreant. Vel an luptatum laboramus, per at illum probatus.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/400x300
          - :name: photo_alignment
            :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: halves
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: "<h2>Heading</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, natum erant
            luptatum ea pri, feugiat minimum eligendi pri ex. Sit eu odio dolores,
            vel noster conceptam ei, ius te sonet philosophia. Eu vix soluta noluisse,
            simul dissentias sea ea, ei eos copiosae oporteat scribentur. Mel cu brute
            quodsi detracto, aperiri accusata adversarium sed an. Omnis sonet mel
            ex, eu mea sint maiorum eligendi. Eu mea utroque abhorreant. Vel an luptatum
            laboramus, per at illum probatus.</p>\r\n"
      - :slug: photo
        :settings:
        - :name: photo_source_url
          :value: http://placehold.it/460x300
        - :name: photo_alignment
          :value: photo-block
- :name: Contact Us
  :title: Contact us at {{client_name}}
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: Looking for contact information for {{client_name}}? Visit our website
          and find it here!
    - :slug: photo
      :settings:
      - :name: photo_source_url
        :value: http://placehold.it/1600x250
      - :name: photo_alignment
        :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h1>Contact {{ client_name }}</h1>\r\n"
        - :slug: lead-form
      - :slug: column
        :row_count: 
        :widgets: []
- :name: Careers
  :title: "{{client_name}} | Career Opritunities"
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: Looking for a Career at {{client_name}}? Visit this page to find out
          more information.
    - :slug: photo
      :settings:
      - :name: photo_source_url
        :value: http://placehold.it/1600x250
      - :name: photo_alignment
        :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h1>Career Opritunities at {{client_name}}</h1>\r\n\r\n<p>Lorem
              ipsum dolor sit amet, natum erant luptatum ea pri, feugiat minimum eligendi
              pri ex. Sit eu odio dolores, vel noster conceptam ei, ius te sonet philosophia.
              Eu vix soluta noluisse, simul dissentias sea ea, ei eos copiosae oporteat
              scribentur. Mel cu brute quodsi detracto, aperiri accusata adversarium
              sed an. Omnis sonet mel ex, eu mea sint maiorum eligendi. Eu mea utroque
              abhorreant. Vel an luptatum laboramus, per at illum probatus.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/360x300
          - :name: photo_alignment
            :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: halves
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h2>Heading</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, natum
              erant luptatum ea pri, feugiat minimum eligendi pri ex. Sit eu odio
              dolores, vel noster conceptam ei, ius te sonet philosophia. Eu vix soluta
              noluisse, simul dissentias sea ea, ei eos copiosae oporteat scribentur.
              Mel cu brute quodsi detracto, aperiri accusata adversarium sed an. Omnis
              sonet mel ex, eu mea sint maiorum eligendi. Eu mea utroque abhorreant.
              Vel an luptatum laboramus, per at illum probatus.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/550x400
          - :name: photo_alignment
            :value: photo-block
- :name: News & Events
  :title: News & Events | {{ client_name }}
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: 'Are you looking for {{client_name}}''s latest news and events? Visit
          our website to find exactly what you are looking for. '
    - :slug: photo
      :settings:
      - :name: photo_source_url
        :value: http://placehold.it/1600x250
      - :name: photo_alignment
        :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h1>Heading</h1>\r\n\r\n<p>Lorem ipsum dolor sit amet, natum
              erant luptatum ea pri, feugiat minimum eligendi pri ex. Sit eu odio
              dolores, vel noster conceptam ei, ius te sonet philosophia. Eu vix soluta
              noluisse, simul dissentias sea ea, ei eos copiosae oporteat scribentur.
              Mel cu brute quodsi detracto, aperiri accusata adversarium sed an. Omnis
              sonet mel ex, eu mea sint maiorum eligendi. Eu mea utroque abhorreant.
              Vel an luptatum laboramus, per at illum probatus.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/450x350
          - :name: photo_alignment
            :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: single
      :widgets:
      - :slug: news-feed
- :name: EEO Statement
  :title: "{{client_name}} | EEO Statement "
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: "{{client_name}} is an Equal Opportunity Employer.  Visit our site
          for our Equal Employment Opportunity statement."
    - :slug: photo
      :settings:
      - :name: photo_source_url
        :value: http://placehold.it/1600x250
      - :name: photo_alignment
        :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h2>Heading</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, natum
              erant luptatum ea pri, feugiat minimum eligendi pri ex. Sit eu odio
              dolores, vel noster conceptam ei, ius te sonet philosophia. Eu vix soluta
              noluisse, simul dissentias sea ea, ei eos copiosae oporteat scribentur.
              Mel cu brute quodsi detracto, aperiri accusata adversarium sed an. Omnis
              sonet mel ex, eu mea sint maiorum eligendi. Eu mea utroque abhorreant.
              Vel an luptatum laboramus, per at illum probatus.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/450x300
          - :name: photo_alignment
            :value: photo-block
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: halves
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h2>Heading</h2>\r\n\r\n<p>Lorem ipsum dolor sit amet, natum
              erant luptatum ea pri, feugiat minimum eligendi pri ex. Sit eu odio
              dolores, vel noster conceptam ei, ius te sonet philosophia. Eu vix soluta
              noluisse, simul dissentias sea ea, ei eos copiosae oporteat scribentur.
              Mel cu brute quodsi detracto, aperiri accusata adversarium sed an. Omnis
              sonet mel ex, eu mea sint maiorum eligendi. Eu mea utroque abhorreant.
              Vel an luptatum laboramus, per at illum probatus.</p>\r\n"
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/600x400
          - :name: photo_alignment
            :value: photo-block
- :name: Privacy Policy
  :title: "{{client_name}} Privacy Policy"
  :enabled: true
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: photo
      :settings:
      - :name: photo_source_url
        :value: http://placehold.it/1600x250
      - :name: photo_alignment
        :value: photo-block
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: "{{client_name}} values your privacy. We collect only the personal
          information you voluntarily provide in order to give the best possible service."
    - :slug: content-stripe
      :row_css_custom: ''
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: one
        :widgets:
        - :slug: html
          :settings:
          - :name: text
            :value: "<h1>Privacy Policy</h1>\r\n\r\n<p><a href=\"https://g5.jiveon.com/docs/DOC-7554\"
              target=\"_blank\">Stock Privacy Policy (Hub)</a></p>\r\n"
      - :slug: column
        :row_count: 
        :widgets: []
