---
:website_template:
  :name: Website Template
  :web_layout:
    :slug: rows
  :web_theme:
    :slug: ivy
  :drop_targets:
  - :html_id: drop-target-head
    :widgets:
    - :slug: meta
    - :slug: typekit
    - :slug: analytics
  - :html_id: drop-target-logo
    :widgets:
    - :slug: logo
  - :html_id: drop-target-phone
    :widgets: []
  - :html_id: drop-target-btn
    :widgets: []
  - :html_id: drop-target-nav
    :widgets:
    - :slug: navigation
      :settings:
      - :name: display_navigation
        :value: 'true'
      - :name: display_as_calls_to_action
        :value: 'false'
      - :name: display_corporate_navigation
        :value: 'false'
  - :html_id: drop-target-aside-before-main
    :widgets:
    - :slug: contact-info-sheet
    - :slug: promoted-reviews
  - :html_id: drop-target-aside-after-main
    :widgets: []
  - :html_id: drop-target-footer
    :widgets:
    - :slug: contact-info
    - :slug: footer-info
:web_home_template:
  :name: Home
  :title: "{{client_name}} Senior Living Facilities"
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: 'Learn about {{client_name}} by visiting our website today. '
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: column
        :row_count: three
        :widgets:
        - :slug: calls-to-action
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/1140x705
        - :slug: home-page-multifamily-iui
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: contact-info
        - :slug: social-links
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: gallery
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: map
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: photo
        :settings:
        - :name: photo_source_url
          :value: http://placehold.it/540x334
      - :slug: social-feed
:web_page_templates:
- :name: Locations
  :title: "{{client_name}} Locations"
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: "{{client_name}} {{page_slug}}."
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: calls-to-action
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/760x470
        - :slug: html
          :settings:
          - :name: text
            :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
              odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem
              risus, commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: contact-info
        - :slug: social-links
- :name: Features
  :title: "{{client_name}} Senior Living Facility Features"
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: "{{client_name}} senior living facilities."
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: calls-to-action
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: photo
          :settings:
          - :name: photo_source_url
            :value: http://placehold.it/760x470
        - :slug: html
          :settings:
          - :name: text
            :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
              odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem
              risus, commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: contact-info
        - :slug: social-links
    - :slug: content-stripe
      :row_layout: thirds
      :widgets:
      - :slug: photo
        :settings:
        - :name: photo_source_url
          :value: http://placehold.it/350x216
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
    - :slug: content-stripe
      :row_layout: halves
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
    - :slug: content-stripe
      :row_layout: quarters
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
    - :slug: content-stripe
      :row_layout: single
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
- :name: Photos
  :title: Photos of Our Senior Living Facilities
  :drop_targets:
  - :html_id: drop-target-main
    :widgets:
    - :slug: meta-description
      :settings:
      - :name: meta_description
        :value: "{{page_name}} of senior living facilities"
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: html
        :settings:
        - :name: text
          :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem risus,
            commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: calls-to-action
    - :slug: content-stripe
      :row_layout: uneven-thirds-2
      :widgets:
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: gallery
        - :slug: html
          :settings:
          - :name: text
            :value: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
              odio nibh, euismod a, lobortis in, laoreet eu, eros. Praesent lorem
              risus, commodo sit amet, viverra in, sagittis nec, justo.
      - :slug: column
        :row_count: two
        :widgets:
        - :slug: contact-info
        - :slug: social-links
